name: Cypress E2E Tests

on:
  push:
    branches:
      - master
      - workflow
  pull_request:
    branches:
      - master
      - workflow

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "21.1.0"

      - name: Install dependencies
        run: npm install

      - name: Build Project
        run: npm run build

      - name: Start Application
        run: npm run start &
        env:
          PORT: 8080

      - name: Wait for Application to be ready
        run: npx wait-on http://localhost:8080

      - name: Run Cypress tests
        uses: cypress-io/github-action@v4
        with:
          browser: electron
