name: Cypress E2E Tests

on:
  push:
    branches:
      - master
      - workflow
  pull_request:
    branches:
      - master
      - workflow

jobs:
  cypress-run:
    name: Run E2E Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout under $GITHUB_WORKSPACE
        uses: actions/checkout@main

      - name: Run Cypress tests
        uses: cypress-io/github-action@v4
        with:
          browser: electron
