name: Lint Code Base

on:
  push:
    branches:
      - master
      - workflow
  pull_request:
    branches:
      - master
      - workflow

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout under $GITHUB_WORKSPACE
        uses: actions/checkout@main

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm install

      - name: Run ESLint
        run: npm run lint
