name: Run Unit Tests

on:
  push:
    branches:
      - master
      - workflow
  pull_request:
    branches:
      - master
      - workflow

jobs:
  test:
    name: Run Unit Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout under $GITHUB_WORKSPACE
        uses: actions/checkout@main

      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "16"

      - name: Install dependencies
        run: npm install

      - name: Run Unit Tests
        run: npm run test-unit
